/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import islandScene from "../assets/3d/island.glb";

const Island = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  currentStage,
  ...props
}) => {
  const islandRef = useRef();
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(islandScene);
  //Speed and Position of Mouse
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handleGrab = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  };
  const handleMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const change = (clientX - lastX.current) / viewport.width;
      rotationSpeed.current = change * Math.PI * 0.015;
      // islandRef.current.rotation.y += change * Math.PI * 0.02;
      lastX.current = clientX;
      // rotationSpeed = change * Math.PI * 0.02;
    }
  };
  const handleUngrab = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };
  const handleKeydown = (e) => {
    if (e.key === "ArrowLeft") {
      if (isRotating) setIsRotating(true);
      rotationSpeed.current = 0.01 * Math.PI;
      // islandRef.current.rotation.y += 0.01 * Math.PI;
    } else if (e.key === "ArrowRight") {
      if (isRotating) setIsRotating(true);
      rotationSpeed.current = -0.01 * Math.PI;
      // islandRef.current.rotation.y -= 0.01 * Math.PI;
    }
  };
  const handleKeyup = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.02) {
        rotationSpeed.current = 0;
      }
    } else {
      const rotation = islandRef.current.rotation.y;
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.024 && normalizedRotation <= 6.08:
          setCurrentStage(5);
          break;
        case normalizedRotation >= 3.768 && normalizedRotation < 4.824:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 2.512 && normalizedRotation < 3.568:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 1.256 && normalizedRotation < 2.312:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 0 && normalizedRotation < 1.056:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
    islandRef.current.rotation.y += rotationSpeed.current;
  });

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handleGrab);
    canvas.addEventListener("pointerup", handleUngrab);
    canvas.addEventListener("pointermove", handleMove);
    document.addEventListener("keydown", handleKeydown);
    document.addEventListener("keyup", handleKeyup);

    return () => {
      canvas.removeEventListener("pointerdown", handleGrab);
      canvas.removeEventListener("pointerup", handleUngrab);
      canvas.removeEventListener("pointermove", handleMove);
      document.removeEventListener("keydown", handleKeydown);
      document.removeEventListener("keyup", handleKeyup);
    };
  }, [gl, handleGrab, handleMove, handleUngrab, handleKeydown, handleKeyup]);

  return (
    <a.group ref={islandRef} {...props}>
      <mesh
        geometry={nodes.polySurface944_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface945_tree1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface946_tree2_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface947_tree1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface948_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface949_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.pCube11_rocks1_0.geometry}
        material={materials.PaletteMaterial001}
      />
    </a.group>
  );
};

export default Island;
